# Generated by Django 2.2.5 on 2019-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='100_1.jpg', upload_to='static/nexus/media/users'),
        ),
    ]
