# Generated by Django 2.2.5 on 2019-10-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_remove_location_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Managers'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
