# Generated by Django 2.2.5 on 2019-09-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190927_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='100_1.jpg', upload_to='profile_pics'),
        ),
    ]
