# Generated by Django 2.2.5 on 2019-10-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard', to=settings.AUTH_USER_MODEL),
        ),
    ]
