# Generated by Django 2.2.5 on 2019-11-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191022_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Guard',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
