# Generated by Django 2.2.5 on 2019-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190927_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='add_one',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='add_two',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
