# Generated by Django 2.2.5 on 2019-10-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
