# Generated by Django 2.2.5 on 2019-10-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0003_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
    ]
