# Generated by Django 2.2.5 on 2019-10-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0004_auto_20191018_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date'], 'verbose_name_plural': 'Entries'},
        ),
    ]
