# Generated by Django 2.2.5 on 2019-11-03 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0009_auto_20191103_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_datetime',
            field=models.DateField(default=datetime.datetime(2019, 11, 3, 11, 17, 32, 963895)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateField(default=datetime.datetime(2019, 11, 3, 11, 17, 32, 963867)),
        ),
    ]
