# Generated by Django 2.2.5 on 2019-11-06 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0014_auto_20191106_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='shift',
            name='status',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='guard',
            name='shift',
        ),
        migrations.AddField(
            model_name='entry',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 35, 14, 186248)),
        ),
        migrations.AddField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 35, 14, 186218)),
        ),
        migrations.AddField(
            model_name='guard',
            name='shift',
            field=models.ManyToManyField(through='attendance_module.ShiftStatus', to='attendance_module.Shift'),
        ),
        migrations.AddField(
            model_name='shiftstatus',
            name='guard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_module.Guard'),
        ),
        migrations.AddField(
            model_name='shiftstatus',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_module.Shift'),
        ),
    ]
