# Generated by Django 2.2.5 on 2019-11-06 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0016_auto_20191106_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 47, 42, 249297)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 21, 47, 42, 249266)),
        ),
    ]
