# Generated by Django 2.2.5 on 2019-11-08 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0019_auto_20191107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 16, 51, 20, 49391)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 16, 51, 20, 49361)),
        ),
    ]
