# Generated by Django 2.2.5 on 2019-11-08 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0020_auto_20191108_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='minutes_worked',
            field=models.IntegerField(default=0, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='entry',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 17, 3, 1, 81081)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 17, 3, 1, 81051)),
        ),
    ]
