# Generated by Django 2.2.5 on 2019-11-16 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0032_auto_20191116_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 0, 27, 42, 327259)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 0, 27, 42, 327226)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.BooleanField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('D', 'Declined')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='leave',
            name='support_docs',
            field=models.FileField(blank=True, null=True, upload_to='support_docs'),
        ),
    ]
