# Generated by Django 2.2.5 on 2019-11-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0033_auto_20191117_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 0, 29, 13, 393676)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 0, 29, 13, 393649)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('D', 'Declined')], default='P', max_length=1),
        ),
    ]
