# Generated by Django 2.2.5 on 2019-11-21 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0037_auto_20191119_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 11, 27, 33, 897311)),
        ),
    ]
