# Generated by Django 2.2.5 on 2019-11-21 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0039_auto_20191121_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 11, 46, 11, 656013)),
        ),
    ]
