# Generated by Django 2.2.5 on 2019-11-21 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_module', '0040_auto_20191121_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 11, 48, 55, 413466)),
        ),
    ]
