# Generated by Django 2.2.5 on 2019-11-16 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_module', '0025_auto_20191116_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_date', models.DateTimeField(default=datetime.datetime(2019, 11, 16, 17, 24, 24, 1255))),
                ('base_pay', models.FloatField(default=0, max_length=32)),
                ('bonus', models.FloatField(default=0, max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_module.Guard')),
            ],
        ),
    ]
