# Generated by Django 2.2.5 on 2019-11-16 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=11, editable=False, max_length=2, unique_for_month=datetime.datetime(2019, 11, 16, 17, 44, 11, 781508)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 17, 44, 11, 781508)),
        ),
    ]
