# Generated by Django 2.2.5 on 2019-11-16 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0003_auto_20191116_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=11, editable=False, max_length=2, unique_for_month='pay_date'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 17, 49, 1, 339292)),
        ),
    ]
