# Generated by Django 2.2.5 on 2019-11-16 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0004_auto_20191116_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 18, 34, 40, 948973)),
        ),
    ]
