# Generated by Django 2.2.5 on 2019-11-16 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0005_auto_20191116_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 18, 56, 6, 877058)),
        ),
    ]
