# Generated by Django 2.2.5 on 2019-11-16 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0007_auto_20191116_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=11, editable=False, max_length=2, unique_for_month='leave_supporting_docs/pay_date'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 16, 23, 28, 24, 393524)),
        ),
    ]
