# Generated by Django 2.2.5 on 2019-11-16 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0008_auto_20191116_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 0, 27, 42, 328630)),
        ),
    ]
