# Generated by Django 2.2.5 on 2019-11-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0009_auto_20191117_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 17, 0, 29, 13, 394736)),
        ),
    ]
