# Generated by Django 2.2.5 on 2019-11-18 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0010_auto_20191117_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 18, 16, 57, 4, 389180)),
        ),
    ]
