# Generated by Django 2.2.5 on 2019-11-18 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0011_auto_20191118_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=11, editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 3, 48, 59, 850815)),
        ),
    ]
