# Generated by Django 2.2.5 on 2019-11-19 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0012_auto_20191119_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'Salaries'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 19, 9, 29, 13, 613402)),
        ),
    ]
