# Generated by Django 2.2.5 on 2019-11-21 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0015_auto_20191121_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(blank=True, editable=False, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 11, 46, 11, 657043)),
        ),
    ]
