# Generated by Django 2.2.5 on 2019-11-21 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_module', '0016_auto_20191121_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='pay_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 21, 11, 48, 55, 414474)),
        ),
    ]
